server:
  port: 8081
  servlet:
    context-path: /com-example

spring:
  profiles:
    active: '@spring.profiles.active@'

  application:
    name: com-example-api

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/static/pages/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  #静态资源本地化读取
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true





